@startuml
!include style.puml
skinparam ActivityBackgroundColor LOGIC_COLOR_T1
skinparam ActivityBorderColor LOGIC_COLOR
skinparam ActivityFontSize 15

start
if (Event exists?) then ([no])
  :Throw "Event not found";
  stop
else ([yes])
  :uniqueNames := removeDuplicates(memberNames);
  while (More names?) is ([yes])
    :name := next uniqueNames;
    if (Member exists?) then ([no])
      :Record missing member;
    else ([yes])
      if (Duplicate entry?) then ([yes])
        :Record duplicate member;
      else ([no])
        :addAttendance;
        :Record added member;
      endif
    endif
  endwhile ([no])
  :build result message;
  stop
endif
@enduml
