@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

ClubHub *-right-> "1" UniquePersonList
ClubHub *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person

Person -up-> "*" Tag

Person *--> Name
Person *--> Year
Person *--> StudentNumber
Person *--> Email
Person *--> Phone
Person *--> DietaryRequirements
Person *--> Role
@enduml
