@startuml
skinparam ArrowFontStyle plain

actor User

box Logic
participant ":LogicManager" as LogicManager
participant ":AddressBookParser" as AddressBookParser
participant "u:UndoCommand" as UndoCommand
end box

box Model
participant ":Model" as Model
end box

[-> LogicManager : execute("undo")
User -> LogicManager : execute("undo")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("undo")
activate AddressBookParser

create UndoCommand
AddressBookParser -> UndoCommand
activate UndoCommand
UndoCommand --> AddressBookParser
deactivate UndoCommand

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> UndoCommand : execute(model)
activate UndoCommand

UndoCommand -> Model : canUndo()
activate Model
Model --> UndoCommand : undoAvailable
deactivate Model

alt canUndo() is false
  UndoCommand --> LogicManager : CommandException
  deactivate UndoCommand
  LogicManager --> User : CommandException
else canUndo() is true
  UndoCommand -> Model : undo()
  activate Model
  Model --> UndoCommand : success
  deactivate Model
  UndoCommand --> LogicManager : CommandResult
  deactivate UndoCommand
  LogicManager --> User : CommandResult
end

destroy UndoCommand
deactivate LogicManager
@enduml
